### ISSUE TITLE
wavemq doesn't exit gracefully

### ISSUE THREAD

**Issue by ddreyer** [immesys/wavemq#1]
Told you about this in person, but just wanted to create an issue here to document it. After running and killing wavemq:

```
$ sudo ./wavemq /etc/wavemq/wavemq.toml
starting metrics on "127.0.0.1:6060"
configuration loaded
2018/11/17 10:09:12 Replaying from value pointer: {Fid:0 Len:44 Offset:37877622}
2018/11/17 10:09:12 Iterating file id: 0
2018/11/17 10:09:12 Iteration took: 12.509µs
GC returns: Value log GC attempt didn't result in any cleanup
XX RESYNC
2018/11/17 10:09:12 Replaying from value pointer: {Fid:0 Len:0 Offset:0}
2018/11/17 10:09:12 Iterating file id: 0
2018/11/17 10:09:12 Iteration took: 75.001µs
Listening for local connections on 127.0.0.1:4516
Listening for peering connections on 0.0.0.0:4515
^CSHUTTING DOWN
```
Waiting several seconds and trying to run it again results in:

```
$ sudo ./wavemq /etc/wavemq/wavemq.toml
starting metrics on "127.0.0.1:6060"
panic: listen tcp 127.0.0.1:6060: bind: address already in use

goroutine 52 [running]:
main.main.func1()
	/home/sgx/go/src/github.com/immesys/wavemq/main.go:53 +0x16d
created by main.main
	/home/sgx/go/src/github.com/immesys/wavemq/main.go:45 +0x58

$ ps aux | grep wavemq
root     28746  1.0  0.2 5487988 42196 ?       Ssl  10:09   0:00 /usr/local/bin/wavemq /etc/wavemq/wavemq.toml
sgx      28780  0.0  0.0  14428  1064 pts/1    S+   10:09   0:00 grep --color=auto wavemq
```

**Comment by ddreyer** [comment]
This hasn't been happening recently, ever since ante.cs got upgraded, so I'm going to close it.
